name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: cd philo && make
      run: cd philo && make
      
    - name: Verify compilation
      run: |
        if [ ! -f ./your_executable ]; then
          echo "Compilation failed"
          exit 1
        fi
